apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: mp2-ghazi
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    persistentvolumeclaims: "4"