apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: mp2-ghazi
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: mp2-ghazi
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: mp2-ghazi
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-viewer
  namespace: mp2-ghazi
automountServiceAccountToken: false