# ⚠️ NE PAS METTRE DE VRAIES VALEURS ICI
# Copier ce fichier en secret.yaml, remplir, puis :
#   kubectl apply -f k8s/10-config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: mp2-ghazi
type: Opaque
stringData:
  POSTGRES_USER: "REMPLACER"
  POSTGRES_PASSWORD: "REMPLACER"